
package MyFrames;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UserListBook extends javax.swing.JInternalFrame {
    
    String params;

    public UserListBook() {
        initComponents();
    }
    
    public UserListBook(String param) {
        initComponents();
        this.setLocation(330,40);
        params = param;
        show_book();
    }
    
    
    public Connection getConnection()
    {
        Connection con;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/perpus_fp", "root", "");
            return con;
        } catch(Exception e)
        {
           return null;
        }
    }
    
    public ArrayList<Book> getBookList()
    {
        ArrayList<Book> bk = new ArrayList<Book>();
        Statement st;
        ResultSet rs;
        try{
            Connection con = getConnection();
            st=con.createStatement();
            String query="SELECT * FROM `book`,`borrow` WHERE `bid`=`bidf` AND `uidf`=(SELECT `id` FROM `users` WHERE `username`='"+params+"');";
            rs=st.executeQuery(query);
            
            Book books;
            
            while(rs.next())
            {
               books = new Book(rs.getInt("bid"),rs.getString("btitle"),rs.getInt("ed"),rs.getInt("pubyear"),rs.getString("publisher"),rs.getString("author"),rs.getInt("quantity"),rs.getInt("price"));
               bk.add(books);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        return bk;
    }
    
        public ArrayList<Borrow> getBorrowList()
    {
        ArrayList<Borrow> bk = new ArrayList<Borrow>();
        Statement st;
        ResultSet rs;
        try{
            Connection con = getConnection();
            st=con.createStatement();
            String query="SELECT * FROM `book`,`borrow` WHERE `bid`=`bidf` AND `uidf`=(SELECT `id` FROM `users` WHERE `username`='"+params+"');";
            rs=st.executeQuery(query);
            
            Borrow borrows;
            
            while(rs.next())
            {
               borrows = new Borrow(rs.getInt("borrowid"),rs.getInt("uidf"),rs.getInt("bidf"),rs.getInt("qbb"),rs.getString("db"),rs.getString("dr"));
               bk.add(borrows);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        return bk;
    }
    
    public void show_book()
    {
        ArrayList<Book> list=getBookList();
        ArrayList<Borrow> list2=getBorrowList();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        Object[] row=new Object[4];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getbid();
            row[1]=list.get(i).getbtitle();
            row[2]=list2.get(i).getdb();
            row[3]=list2.get(i).getdr();
            model.addRow(row);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("User's Issued Book");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("User's Issued Book List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Title", "Issued Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
